Repository engaging-computing/MYR, pull requests merged in 2018-10, with the labels that each got.

#41 Dev
  src/actions/projectActions.js
  src/components/Header.js
  src/components/Lesson.js
  src/components/ProjectView.js
  src/components/SceneConfig.js
  src/components/Sidebar.js
  src/containers/Guided.js
  src/containers/Ide.js
  src/css/App.css
  src/myr/Myr.js
  src/reducers/project.js
  src/store.js
Labels: bug, enhancement

#46 added tube and line to MYR API
  src/components/View.js
  src/myr/Myr.js
Labels: enhancement

#47 Logout Bug and Lesson Nav Button Fix
  src/components/Lesson.js
  src/firebase.js
Labels: bug

#50 Dev
  src/components/Footer.js
  src/containers/Guided.js
  src/containers/Ide.js
  src/css/App.css
Labels: enhancement
