Repository engaging-computing/MYR, pull requests merged in 2019-03, with the labels that each got.

#119 Polish/doc
  package.json
  src/components/Reference.js
  src/css/App.css
  src/myr/reference.js
Labels: enhancement

#120 Redux refactor and Reference update
  package.json
  src/actions/authActions.js
  src/actions/courseActions.js
  src/actions/editorActions.js
  src/actions/index.js
  src/actions/projectActions.js
  src/actions/sceneActions.js
  src/components/Editor.js
  src/components/Reference.js
  src/constants/ActionTypes.js
  src/containers/Guided.js
  src/containers/Ide.js
  src/css/App.css
  src/firebase.js
  src/index.js
  src/myr/Myr.js
  src/myr/reference.js
  src/reducers/course.js
  src/reducers/editor.js
  src/reducers/index.js
  src/reducers/project.js
  src/reducers/scene.js
  src/reducers/user.js
Labels: Redesign, enhancement

#127 Phi length added in all geometries that support it
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  src/myr/Myr.js
Labels: enhancement

#129 Classroom submissions
  package.json
  src/actions/classroomActions.js
  src/actions/index.js
  src/actions/projectActions.js
  src/actions/sceneActions.js
  src/components/Classroom.js
  src/components/Editor.js
  src/components/Header.js
  src/components/SceneConfigMenu.js
  src/components/View.js
  src/components/classroom/SelectProject.js
  src/components/customCompleter.js
  src/constants/ActionTypes.js
  src/containers/Classroom.js
  src/containers/Ide.js
  src/css/App.css
  src/css/Classroom.css
  src/firebase.js
  src/reducers/classes.js
  src/reducers/index.js
  src/reducers/scene.js
  src/routes.js
  src/utils/AframeReg.js
  yarn.lock
Labels: Frontend, Redesign, enhancement
