Repository engaging-computing/MYR, pull requests merged in 2019-06, with the labels that each got.

#180 Reference comes from the right, dependency update, color shift animation, animations use the cursor, scene config doesn't lose work, and tour can highlight editor
  LICENSE
  src/actions/sceneActions.js
  src/components/Header.js
  src/components/MyrTour.js
  src/components/Reference.js
  src/components/SceneConfigMenu.js
  src/components/customCompleter.js
  src/css/App.css
  src/myr/Myr.js
  src/myr/reference.js
  src/tests/Myr.test.js
  yarn.lock
Labels: Frontend, MYR API, Redesign, Redux, UI/UX, bug, dependencies, enhancement

#192 Made close and open in new tab buttons in reference colored
  src/components/CourseSelect.js
  src/components/Reference.js
  src/components/SceneConfigMenu.js
Labels: UI/UX, enhancement

#191 Fixed bug where tour could open with reference open, and also disables tour when reference page was opened.
  src/components/Header.js
  src/components/MyrTour.js
  src/components/Reference.js
Labels: UI/UX, bug
