Repository engaging-computing/MYR, pull requests merged in 2022-08, with the labels that each got.

#610 Scene title and description editing
  src/components/structural/WelcomeScreen.js
  src/components/structural/header/Header.js
  src/components/structural/header/ProjectView.js
Labels: enhancement, Frontend, Discussion needed, UI/UX

#595 Created new buttons in the settings to reset color and toggle cursor
  src/actions/sceneActions.js
  src/components/structural/View.js
  src/components/structural/header/SceneConfigMenu.js
  src/constants/ActionTypes.js
  src/css/SceneConfig.css
  src/reducers/scene.js
  src/tests/App.test.js
Labels: enhancement, Frontend

#606 changed the "usersettings" prop to lowercase across all layout files
  src/components/layouts/Collection.js
  src/components/layouts/ReferenceExample.js
Labels: enhancement

#582 Added a progress bar to courses (Done by Ryan and myself)
  src/components/courses/Course.js
Labels: enhancement, Frontend

#581 Copy line
  package-lock.json
  package.json
  src/components/editor/Editor.js
  src/components/editor/KeyboardShortcut.js
Labels: enhancement, Frontend

#617 Fix for scaling in groups
  src/myr/Myr.js
Labels: Frontend, Minor bug

#619 Added new hover effect to project view
  src/components/structural/Footer.js
  src/components/structural/header/ProjectView.js
  src/css/ProjectView.css
Labels: enhancement, Frontend, Redesign, Discussion needed, UI/UX, dev

#621 Updated the Speed Slider UI to make more user-friendly
  src/components/structural/header/SceneConfigMenu.js
Labels: enhancement, Frontend, UI/UX

#629 Added movement controls to welcome screen
  src/components/structural/WelcomeScreen.js
Labels: enhancement, Frontend, Redesign

#630 Changed the support page link
  src/components/structural/Footer.js
Labels: enhancement, Frontend
